# ==============================================================
# api/routes/content.py — Creative Content Generation (CaaS + RAG)
# ==============================================================

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import text
from datetime import datetime
import json
import traceback

from api.connection import get_db
from api.services.prompts.prompt_content import generate_content_prompt
from api.services.image_gen_service import generate_image_from_brief

# ✅ FIXED: Define router properly so FastAPI can include it
router = APIRouter(prefix="/content", tags=["Content"])


# ==============================================================
# 🔹 POST /content/generate
# ==============================================================
@router.post("/generate")
def generate_content(request: dict, db: Session = Depends(get_db)):
    """
    Generate AI-powered marketing content (Facebook, Instagram, Blog, etc.)
    using the dual-model AI chain and optionally create visuals/videos.
    This endpoint produces only *creative content* — not strategy.
    """

    # ✅ Step 1 — Input validation
    business_name = request.get("business_name")
    industry = request.get("industry")
    goal = request.get("goal")
    content_type = request.get("content_type", "instagram_post")
    enable_visuals = request.get("enable_visuals", False)
    enable_video = request.get("enable_video", False)

    if not all([business_name, industry, goal]):
        raise HTTPException(
            status_code=400,
            detail="Missing required fields: business_name, industry, or goal."
        )

    # ✅ Step 2 — Generate AI content
    try:
        llm_response = generate_content_prompt(
            business_name=business_name,
            industry=industry,
            goal=goal,
            content_type=content_type,
            enable_rag=True,          # 🔹 Enables RAG context
            enable_web_search=True    # 🔹 Adds web trend enrichment
        )
    except Exception as e:
        error_trace = traceback.format_exc()
        raise HTTPException(
            status_code=500,
            detail=f"AI content generation failed: {str(e)}\n{error_trace}"
        )

    # ✅ Step 3 — Parse structured output
    content_block = llm_response.get("content", "")
    if isinstance(content_block, dict):
        refined_content = json.dumps(content_block, indent=2)
        content_json = content_block
    else:
        refined_content = str(content_block).strip()
        content_json = {"raw_text": refined_content}

    if not refined_content:
        raise HTTPException(status_code=500, detail="No content generated by AI.")

    # ✅ Step 4 — Conditional visual/video generation
    visual_result, video_result = None, None

    if enable_visuals:
        ai_visual_brief = content_json.get("ai_visual_brief", {})
        if ai_visual_brief:
            visual_result = generate_image_from_brief(ai_visual_brief, auto_trigger=True)
        else:
            visual_result = {"status": "skipped", "reason": "No visual brief provided."}

    if enable_video:
        try:
            from api.services.video_gen_service import generate_video_from_brief
            ai_video_brief = content_json.get("ai_visual_brief", {}).get("video_prompt")
            if ai_video_brief:
                video_result = generate_video_from_brief(ai_video_brief)
            else:
                video_result = {"status": "skipped", "reason": "No video brief provided."}
        except ImportError:
            video_result = {"status": "skipped", "reason": "Video generation module not found."}

    # ✅ Step 5 — Save to database
    try:
        db.execute(
            text("""
                INSERT INTO contents (business_id, type, title, body, hashtags, platform, created_at)
                VALUES (:business_id, :type, :title, :body, :hashtags, :platform, :created_at)
            """),
            {
                "business_id": 1,  # ⚠️ Placeholder — replace with actual user ID when auth is added
                "type": content_type,
                "title": f"{content_type.replace('_', ' ').title()} for {business_name}",
                "body": refined_content,
                "hashtags": json.dumps(content_json.get("hashtags", ["#AIContent", "#MarketingAdvantageAI", "#Growth"])),
                "platform": content_type.split("_")[0],
                "created_at": datetime.utcnow()
            }
        )
        db.commit()
    except Exception as e:
        db.rollback()
        error_trace = traceback.format_exc()
        raise HTTPException(
            status_code=500,
            detail=f"Database insert failed: {str(e)}\n{error_trace}"
        )

    # ✅ Step 6 — Structured, smart response
    return {
        "status": "success",
        "message": f"{content_type.replace('_', ' ').title()} generated successfully for {business_name}.",
        "metadata": {
            "business_name": business_name,
            "industry": industry,
            "goal": goal,
            "content_type": content_type,
            "models_used": llm_response.get("models_used"),
            "execution_time_sec": llm_response.get("execution_time_sec"),
            "from_cache": llm_response.get("from_cache", False),
            "temperature": llm_response.get("temperature", 0.8),
            "visual_generation": enable_visuals,
            "video_generation": enable_video,
        },
        "content": content_json,     # ✅ structured JSON for UI
        "raw_text": refined_content, # ✅ plain text for logging
        "visual": visual_result,     # ✅ image result if generated
        "video": video_result        # ✅ video result if available
    }
