from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy.sql import text
from datetime import datetime
import json
import traceback

from api.connection import get_db
from api.services.prompts.prompt_strategy import generate_strategy_prompt
from api.services.image_gen_service import generate_image_from_brief

router = APIRouter(prefix="/strategy", tags=["Strategy"])


# ==========================================================
# 🔹 POST /strategy/generate
# ==========================================================
@router.post("/generate")
def generate_strategy(request: dict, db: Session = Depends(get_db)):
    """
    Generate an advanced AI-powered marketing strategy using the dual-model chain
    (LLaMA → DeepSeek), optionally enriched with image or video generation.
    Stores structured strategy data in PostgreSQL.
    """

    # ✅ Step 1 — Validate request
    business_name = request.get("business_name")
    industry = request.get("industry")
    goal = request.get("goal")
    specialization = request.get("specialization", "data_driven")
    enable_visuals = bool(request.get("enable_visuals", False))
    enable_video = bool(request.get("enable_video", False))

    if not all([business_name, industry, goal]):
        raise HTTPException(
            status_code=400,
            detail="Missing required fields: business_name, industry, or goal"
        )

    # ✅ Step 2 — Generate Strategy (Dual-Model)
    try:
        llm_response = generate_strategy_prompt(
            business_name=business_name,
            industry=industry,
            goal=goal,
            specialization=specialization
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"AI generation failed: {str(e)}\n{traceback.format_exc()}"
        )

    # ✅ Step 3 — Parse strategy output
    content_block = llm_response.get("content", "")
    if isinstance(content_block, dict):
        refined_strategy = json.dumps(content_block, indent=2)
        strategy_json = content_block
    else:
        refined_strategy = str(content_block).strip()
        strategy_json = {"raw_text": refined_strategy}

    if not refined_strategy:
        raise HTTPException(status_code=500, detail="No strategy generated by AI models")

    # ✅ Step 4 — Optional Visual and Video Generation
    visual_result, video_result = None, None

    # --- Image Generation (DeepAI / DALL·E / Diffusers) ---
    if enable_visuals:
        ai_visual_brief = strategy_json.get("ai_visual_brief", {
            "image_prompt": f"Visualize the marketing strategy for {business_name} in {industry}. "
                            f"Goal: {goal}. Include data-driven and creative themes.",
            "style": "strategic and modern infographic",
            "color_palette": "brand-consistent, professional",
            "mood": "analytical yet inspiring"
        })
        try:
            visual_result = generate_image_from_brief(ai_visual_brief, auto_trigger=True)
        except Exception as e:
            visual_result = {"status": "error", "reason": str(e)}

    # --- Video Generation (optional future expansion) ---
    if enable_video:
        try:
            from api.services.video_gen_service import generate_video_from_brief
            ai_video_prompt = strategy_json.get("ai_visual_brief", {}).get(
                "video_prompt",
                f"Create a short explainer video summarizing {business_name}'s marketing strategy for {goal}."
            )
            video_result = generate_video_from_brief(ai_video_prompt)
        except ImportError:
            video_result = {"status": "skipped", "reason": "Video generation module not available."}
        except Exception as e:
            video_result = {"status": "error", "reason": str(e)}

    # ✅ Step 5 — Save Strategy to Database
    try:
        db.execute(
            text("""
                INSERT INTO strategies (business_id, summary, channels, uvp, growth_plan, created_at)
                VALUES (:business_id, :summary, :channels, :uvp, :growth_plan, :created_at)
            """),
            {
                "business_id": 1,  # ⚠️ Replace with actual authenticated user's ID
                "summary": refined_strategy[:500],
                "channels": json.dumps(strategy_json.get("channels", [
                    "Social Media",
                    "SEO",
                    "Email Marketing",
                    "Influencer Partnerships"
                ])),
                "uvp": f"AI-Driven Strategy for {business_name} in {industry}",
                "growth_plan": json.dumps(strategy_json),
                "created_at": datetime.utcnow(),
            },
        )
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Database insert failed: {str(e)}\n{traceback.format_exc()}"
        )

    # ✅ Step 6 — Return structured multi-modal response
    return {
        "status": "success",
        "message": f"Marketing strategy for '{business_name}' generated successfully.",
        "metadata": {
            "business_name": business_name,
            "industry": industry,
            "goal": goal,
            "specialization": specialization,
            "models_used": llm_response.get("models_used"),
            "execution_time_sec": llm_response.get("execution_time_sec"),
            "from_cache": llm_response.get("from_cache", False),
            "temperature": llm_response.get("temperature", 0.8),
            "visual_generation": enable_visuals,
            "video_generation": enable_video
        },
        "strategy": strategy_json,   # ✅ Structured JSON for dashboard/UI
        "raw_text": refined_strategy,  # ✅ Readable version for logs or exports
        "visual": visual_result,     # ✅ Optional image generation info
        "video": video_result        # ✅ Optional video generation info
    }
